# Semgrep configuration for Kubeli
# https://semgrep.dev/docs/writing-rules/rule-syntax/

rules:
  # Prevent console.log in production code (except debug wrappers)
  - id: no-console-log-in-prod
    patterns:
      - pattern: console.log(...)
      - pattern-not-inside: |
          const debug = (...) => { ... console.log(...) ... }
      - pattern-not-inside: |
          function debug(...) { ... console.log(...) ... }
    paths:
      include:
        - /src/
      exclude:
        - /src/**/*.test.*
        - /src/**/*.spec.*
    message: "Remove console.log before production"
    languages: [typescript, javascript]
    severity: WARNING

  # Prevent unsafe innerHTML usage
  - id: no-dangerouslySetInnerHTML
    pattern: dangerouslySetInnerHTML={...}
    message: "Avoid dangerouslySetInnerHTML - XSS risk"
    languages: [typescript, javascript]
    severity: ERROR
