---
# ResourceQuota for the namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: demo-quota
  namespace: kubeli-demo
  labels:
    app: kubeli-demo
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    pods: "20"
    services: "10"
    secrets: "20"
    configmaps: "20"
    persistentvolumeclaims: "5"
---
# LimitRange for containers
apiVersion: v1
kind: LimitRange
metadata:
  name: demo-limit-range
  namespace: kubeli-demo
  labels:
    app: kubeli-demo
spec:
  limits:
    - type: Container
      default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      max:
        cpu: "2"
        memory: 2Gi
      min:
        cpu: 50m
        memory: 64Mi
    - type: PersistentVolumeClaim
      max:
        storage: 10Gi
      min:
        storage: 100Mi
