# Flux CD HelmRelease CRD for local testing
# This is a minimal CRD definition to allow creating HelmRelease resources
# For production, use the full Flux installation
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helmreleases.helm.toolkit.fluxcd.io
spec:
  group: helm.toolkit.fluxcd.io
  names:
    kind: HelmRelease
    listKind: HelmReleaseList
    plural: helmreleases
    shortNames:
      - hr
    singular: helmrelease
  scope: Namespaced
  versions:
    - name: v2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                chart:
                  type: object
                  properties:
                    spec:
                      type: object
                      properties:
                        chart:
                          type: string
                        version:
                          type: string
                        sourceRef:
                          type: object
                          properties:
                            kind:
                              type: string
                            name:
                              type: string
                interval:
                  type: string
                releaseName:
                  type: string
                targetNamespace:
                  type: string
                values:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                lastAppliedRevision:
                  type: string
                lastAttemptedRevision:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: Ready
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].status
        - name: Status
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].message
    - name: v2beta2
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                chart:
                  type: object
                  properties:
                    spec:
                      type: object
                      properties:
                        chart:
                          type: string
                        version:
                          type: string
                        sourceRef:
                          type: object
                          properties:
                            kind:
                              type: string
                            name:
                              type: string
                interval:
                  type: string
                releaseName:
                  type: string
                targetNamespace:
                  type: string
                values:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                lastAppliedRevision:
                  type: string
                lastAttemptedRevision:
                  type: string
      subresources:
        status: {}
