# Scale Test Template for local testing
# Base template used by scripts/k8s-scale.sh to generate N dummy pods
# This file serves as reference - actual pods are generated dynamically

---
# Namespace for scale testing
apiVersion: v1
kind: Namespace
metadata:
  name: kubeli-scale-test
  labels:
    app.kubernetes.io/part-of: kubeli-testing
    purpose: scale-testing

---
# ResourceQuota to prevent runaway resource usage
apiVersion: v1
kind: ResourceQuota
metadata:
  name: scale-test-quota
  namespace: kubeli-scale-test
spec:
  hard:
    pods: "500"
    requests.cpu: "50"
    requests.memory: 10Gi
    limits.cpu: "100"
    limits.memory: 20Gi

---
# LimitRange for default resource constraints
apiVersion: v1
kind: LimitRange
metadata:
  name: scale-test-limits
  namespace: kubeli-scale-test
spec:
  limits:
    - type: Container
      default:
        cpu: 50m
        memory: 64Mi
      defaultRequest:
        cpu: 10m
        memory: 32Mi
      max:
        cpu: 200m
        memory: 256Mi
      min:
        cpu: 5m
        memory: 16Mi

# Template Pod definition is embedded in scripts/k8s-scale.sh
# The script generates pods dynamically with names like scale-pod-{N}
