import type { Column, TranslateFunc } from "../types";

// Column label to translation key mapping
const columnLabelToKey: Record<string, string> = {
  "NAME": "columns.name",
  "NAMESPACE": "columns.namespace",
  "READY": "columns.ready",
  "STATUS": "columns.status",
  "RESTARTS": "columns.restarts",
  "NODE": "columns.node",
  "AGE": "columns.age",
  "AVAILABLE": "columns.available",
  "TYPE": "columns.type",
  "CLUSTER IP": "columns.clusterIp",
  "PORTS": "columns.ports",
  "DATA": "columns.data",
  "HOLDER": "columns.holder",
  "DURATION": "columns.duration",
  "TRANSITIONS": "columns.transitions",
  "LAST RENEWED": "columns.lastRenewed",
  "OWNER": "columns.owner",
  "DESIRED": "columns.desired",
  "CURRENT": "columns.current",
  "SERVICE": "columns.service",
  "COMPLETIONS": "columns.completions",
  "SCHEDULE": "columns.schedule",
  "SUSPEND": "columns.suspend",
  "ACTIVE": "columns.active",
  "ACTIVE JOBS": "columns.activeJobs",
  "LAST SCHEDULE": "columns.lastSchedule",
  "CLASS": "columns.class",
  "HOSTS": "columns.hosts",
  "ADDRESS": "columns.address",
  "TLS": "columns.tls",
  "ADDRESS TYPE": "columns.addressType",
  "ENDPOINTS": "columns.endpoints",
  "POLICY TYPES": "columns.policyTypes",
  "POD SELECTOR": "columns.podSelector",
  "INGRESS": "columns.ingress",
  "EGRESS": "columns.egress",
  "CONTROLLER": "columns.controller",
  "PARAMETERS": "columns.parameters",
  "REFERENCE": "columns.reference",
  "MIN": "columns.min",
  "MAX": "columns.max",
  "REPLICAS": "columns.replicas",
  "LIMITS": "columns.limits",
  "TYPES": "columns.types",
  "RESOURCES": "columns.resources",
  "SCOPES": "columns.scopes",
  "MIN AVAILABLE": "columns.minAvailable",
  "MAX UNAVAILABLE": "columns.maxUnavailable",
  "ALLOWED": "columns.allowed",
  "PODS": "columns.pods",
  "CAPACITY": "columns.capacity",
  "ACCESS MODES": "columns.accessModes",
  "RECLAIM POLICY": "columns.reclaimPolicy",
  "CLAIM": "columns.claim",
  "STORAGE CLASS": "columns.storageClass",
  "VOLUME": "columns.volume",
  "PROVISIONER": "columns.provisioner",
  "VOLUME BINDING MODE": "columns.volumeBindingMode",
  "EXPANSION": "columns.expansion",
  "ATTACH REQUIRED": "columns.attachRequired",
  "POD INFO": "columns.podInfo",
  "STORAGE CAPACITY": "columns.storageCapacity",
  "MODES": "columns.modes",
  "DRIVERS": "columns.drivers",
  "DRIVER NAMES": "columns.driverNames",
  "ATTACHER": "columns.attacher",
  "PV": "columns.pv",
  "ATTACHED": "columns.attached",
  "SECRETS": "columns.secrets",
  "IMAGE PULL SECRETS": "columns.imagePullSecrets",
  "AUTOMOUNT TOKEN": "columns.automountToken",
  "RULES": "columns.rules",
  "ROLE": "columns.role",
  "SUBJECTS": "columns.subjects",
  "AGGREGATION LABELS": "columns.aggregationLabels",
  "GROUP": "columns.group",
  "KIND": "columns.kind",
  "SCOPE": "columns.scope",
  "VERSIONS": "columns.versions",
  "VALUE": "columns.value",
  "PREEMPTION": "columns.preemption",
  "DESCRIPTION": "columns.description",
  "HANDLER": "columns.handler",
  "TOLERATIONS": "columns.tolerations",
  "NODE SELECTOR": "columns.nodeSelector",
  "WEBHOOKS": "columns.webhooks",
  "SERVICES": "columns.services",
  "FAILURE POLICY": "columns.failurePolicy",
  "CHART": "columns.chart",
  "APP VERSION": "columns.appVersion",
  "REVISION": "columns.revision",
  "UPDATED": "columns.updated",
  "REASON": "columns.reason",
  "OBJECT": "columns.object",
  "MESSAGE": "columns.message",
  "COUNT": "columns.count",
  "LAST SEEN": "columns.lastSeen",
  "ROLES": "columns.roles",
  "VERSION": "columns.version",
  "INTERNAL IP": "columns.internalIp",
  "LABELS": "columns.labels",
  "ACTIONS": "columns.actions",
};

/** Translate column labels using the columnLabelToKey mapping */
export function translateColumns<T>(columns: Column<T>[], t: TranslateFunc): Column<T>[] {
  return columns.map(col => ({
    ...col,
    label: columnLabelToKey[col.label] ? t(columnLabelToKey[col.label]) : col.label,
  }));
}
